output "resource_names" {
  description = "Representative names generated by the Advocate Health naming module."
  value = {
    management_group = module.management_group_name.name
    public_ip        = module.public_ip_name.name
    resource_group   = module.resource_group_name.name
    storage_account  = module.storage_account_name.name
    subnet           = module.subnet_name.name
    virtual_network  = module.virtual_network_name.name
  }
}
